# Generated by Django 3.0.5 on 2020-12-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend_category',
            name='id',
            field=models.CharField(default=(1, 2), max_length=10),
            preserve_default=False,
        ),
    ]
