# Generated by Django 3.0.5 on 2020-12-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0002_legend_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council_Category',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='hostel2/static/hostel2/Images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel2.Council_Category')),
            ],
        ),
    ]
