# Generated by Django 3.1.4 on 2020-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0005_council_councillor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CultCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventsCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaintCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SportsCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TechCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(max_length=150)),
                ('conatctno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Council',
        ),
        migrations.DeleteModel(
            name='Council_Category',
        ),
    ]
