# Generated by Django 3.1.4 on 2020-12-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0007_admincouncil_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='cultcouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='eventscouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='maintcouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='messcouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='sportscouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='techcouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='webcouncil',
            old_name='conatctno',
            new_name='contactno',
        ),
    ]
