# Generated by Django 3.1.4 on 2020-12-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0008_auto_20201222_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincouncil',
            name='rollno',
        ),
        migrations.AlterField(
            model_name='admincouncil',
            name='contactno',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='admincouncil',
            name='roomno',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
