# Generated by Django 3.1.4 on 2020-12-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0009_auto_20201222_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultcouncil',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='eventscouncil',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='maintcouncil',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='messcouncil',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='sportscouncil',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='techcouncil',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='webcouncil',
            name='rollno',
        ),
    ]
