# Generated by Django 3.1.4 on 2020-12-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0012_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='update',
            field=models.CharField(default='No new Updates', max_length=150, primary_key=True, serialize=False),
        ),
    ]
