# Generated by Django 3.1.4 on 2020-12-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0014_auto_20201223_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='update',
        ),
        migrations.AlterField(
            model_name='updates',
            name='name',
            field=models.CharField(default='No New Update', max_length=150, primary_key=True, serialize=False),
        ),
    ]
