# Generated by Django 3.0.5 on 2021-01-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0017_auto_20201227_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniTestimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=150)),
                ('testimony', models.CharField(max_length=150)),
            ],
        ),
    ]
