# Generated by Django 3.0.5 on 2021-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0018_alumnitestimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnitestimony',
            name='testimony',
            field=models.CharField(max_length=5000),
        ),
    ]
