# Generated by Django 3.0.5 on 2021-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0019_auto_20210108_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnitestimony',
            name='testimony',
            field=models.TextField(max_length=5000),
        ),
    ]
