# Generated by Django 3.0.5 on 2021-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0020_auto_20210108_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnitestimony',
            name='pic',
            field=models.ImageField(default=333, upload_to=''),
            preserve_default=False,
        ),
    ]
