# Generated by Django 3.0.5 on 2021-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0022_auto_20210108_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnitestimony',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='testimonial/'),
        ),
    ]
