# Generated by Django 3.0.8 on 2021-01-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0024_post'),
        ('hostel2', '0023_post'),
    ]

    operations = [
    ]
