# Generated by Django 3.0.8 on 2021-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0025_merge_20210111_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admincouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='cultcouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultcouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='eventscouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventscouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='maintcouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintcouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='messcouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messcouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='sportscouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportscouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='techcouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techcouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='webcouncil',
            name='manifestoExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webcouncil',
            name='socialmedia',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
