# Generated by Django 3.0.5 on 2021-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0026_auto_20210112_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
    ]
