# Generated by Django 3.0.5 on 2021-01-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0027_admincouncil_manifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultcouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
        migrations.AddField(
            model_name='eventscouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
        migrations.AddField(
            model_name='maintcouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
        migrations.AddField(
            model_name='messcouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
        migrations.AddField(
            model_name='sportscouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
        migrations.AddField(
            model_name='techcouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
        migrations.AddField(
            model_name='webcouncil',
            name='manifesto',
            field=models.FileField(default='', upload_to='manifesto/'),
        ),
    ]
