# Generated by Django 3.0.8 on 2021-01-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0029_auto_20210118_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council_Category',
            fields=[
                ('category', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='admincouncil',
            name='manifesto',
            field=models.FileField(blank=True, null=True, upload_to='manifesto/'),
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('roomno', models.CharField(blank=True, default='', max_length=150)),
                ('contactno', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/')),
                ('councillor', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=True)),
                ('manifestoExists', models.BooleanField(default=False)),
                ('socialmedia', models.CharField(default='#', max_length=150)),
                ('manifesto', models.FileField(blank=True, null=True, upload_to='manifesto/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel2.Council_Category')),
            ],
        ),
    ]
