# Generated by Django 3.0.8 on 2021-01-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0030_auto_20210121_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminCouncil',
        ),
        migrations.DeleteModel(
            name='CultCouncil',
        ),
        migrations.DeleteModel(
            name='EventsCouncil',
        ),
        migrations.DeleteModel(
            name='MaintCouncil',
        ),
        migrations.DeleteModel(
            name='MessCouncil',
        ),
        migrations.DeleteModel(
            name='SportsCouncil',
        ),
        migrations.DeleteModel(
            name='TechCouncil',
        ),
        migrations.DeleteModel(
            name='WebCouncil',
        ),
    ]
