# Generated by Django 3.0.8 on 2021-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0031_auto_20210121_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='style',
            field=models.CharField(default='Card1', max_length=150),
        ),
    ]
