# Generated by Django 3.0.8 on 2021-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0032_council_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='style',
            field=models.CharField(default='card1', max_length=150),
        ),
    ]
