# Generated by Django 3.0.8 on 2021-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0033_auto_20210121_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='headingcolor',
            field=models.CharField(default='black', max_length=150),
        ),
    ]
