# Generated by Django 3.0.5 on 2021-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0037_auto_20210121_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
