# Generated by Django 3.0.5 on 2021-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0039_auto_20210122_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='manifesto',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AlterField(
            model_name='council',
            name='picture',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
