# Generated by Django 3.0.5 on 2021-01-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0040_auto_20210122_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='council_category',
            name='order',
            field=models.IntegerField(default=2, max_length=150),
        ),
    ]
