# Generated by Django 3.0.5 on 2021-01-22 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel2', '0042_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
