# Generated by Django 3.0.8 on 2021-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_1',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_2',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_3',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_4',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_5',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gc_participation',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_cult',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_sports',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_tech',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_e_certificates',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(default='None', max_length=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(default='0'),
        ),
    ]
