# Generated by Django 3.0.8 on 2021-01-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210111_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://bootdey.com/img/Content/avatar/avatar7.png', upload_to='profile_pics'),
        ),
    ]
