# Generated by Django 3.0.8 on 2020-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201220_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gc_participation',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
