# Generated by Django 3.0.8 on 2021-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210113_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/avatar7.png', upload_to='profile_pics'),
        ),
    ]
