# Generated by Django 3.1.4 on 2020-12-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificates',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
