# Generated by Django 3.0.5 on 2021-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210113_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
