# Generated by Django 3.1.4 on 2020-12-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201228_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='field_name',
            new_name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='color',
        ),
    ]
