# Generated by Django 3.0.8 on 2021-01-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210114_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests_cult',
            field=models.CharField(blank=True, default='Edit profile to select interest', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests_sports',
            field=models.CharField(blank=True, default='Edit profile to select interest', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests_tech',
            field=models.CharField(blank=True, default='Edit profile to select interest', max_length=100),
        ),
    ]
