# Generated by Django 3.0.8 on 2021-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210104_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='e_certificates',
            new_name='e_certificate_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='interests',
            new_name='interests_cult',
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_2',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_3',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_4',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_5',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_sports',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_tech',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_e_certificates',
            field=models.IntegerField(default='0'),
        ),
    ]
