# Generated by Django 3.1.4 on 2021-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210104_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_certificates',
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_i',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_e_certificates',
            field=models.IntegerField(default='0'),
        ),
    ]
