# Generated by Django 3.1.4 on 2021-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210110_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_certificate_i',
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_1',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_2',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_3',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_4',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_5',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
    ]
