# Generated by Django 3.1.4 on 2021-01-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210110_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='e_certificate_1',
            new_name='e_certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_certificate_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_certificate_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_certificate_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_certificate_5',
        ),
    ]
