# Generated by Django 3.1.4 on 2021-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210110_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interests',
            new_name='interests_cult',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_sports',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_tech',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
