# Generated by Django 3.1.4 on 2021-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210110_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_certificates', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='e_certificate',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
