# Generated by Django 3.1.4 on 2021-01-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210110_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='user_ec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
