# Generated by Django 3.1.4 on 2021-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_postimage_user_ec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_certificate',
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_1',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_2',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_3',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_4',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_certificate_5',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
